-- user 기본값
-- UUID() ISSUE
-- insert into user (uuid, nickname, password, role)
-- values (UUID(), '레이머', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'ROLE_USER');
-- insert into user (uuid, nickname, password, role)
-- values (UUID(), 'Rosie', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'ROLE_USER');
-- insert into user (uuid, nickname, password, role)
-- values (UUID(), '영민', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'ROLE_USER');

-- tag 기본값
-- insert into tag (tag) values ('블로그');